package com.lx.dao;

import com.lx.model.UserCollectVideo;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserCollectVideoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_collect_video
     *
     * @mbggenerated
     */
    int insert(UserCollectVideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_collect_video
     *
     * @mbggenerated
     */
    int insertSelective(UserCollectVideo record);

    Integer user_collect_video_count(Integer vid);

    Integer if_collect(@Param("userid") Integer userid,@Param("vid") Integer vid);

    Integer cancel_collect(@Param("userid") Integer userid,@Param("vid")Integer vid);

    int collect(UserCollectVideo record);

    List<UserCollectVideo> user_collect_videos(Integer userid);
}