package com.lx.dao;

import com.lx.model.UserPraiseIcon;
import org.apache.ibatis.annotations.Param;

public interface UserPraiseIconMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_praise_icon
     *
     * @mbggenerated
     */
    int insert(UserPraiseIcon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_praise_icon
     *
     * @mbggenerated
     */
    int insertSelective(UserPraiseIcon record);

    int praised(@Param("userids") Integer userid, @Param("vids") Integer vid);  //点赞

    int Cancel_praised(@Param("userids") Integer userid,@Param("vids") Integer vid);//取消点赞



    Integer if_praised(@Param("userid") Integer userid,@Param("vid") Integer vid);  //判断是否点赞

    int add_praise_tab(@Param("statePraise") Integer statePraise,@Param("userid") Integer userid ,@Param("vid") Integer vid);   //加入点赞记录

    int giveCoined(@Param("userid") Integer userid ,@Param("vid") Integer vid); //投币

    Integer if_giveCoin(@Param("userid") Integer userid,@Param("vid") Integer vid);//判断是否投币

    int add_Coin_tab(@Param("stateIcon") Integer stateIcon,@Param("userid") Integer userid ,@Param("vid") Integer vid); //加入投币记录
}