package com.lx.model;

public class Follow {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column follow.userid
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column follow.follow_id
     *
     * @mbggenerated
     */
    private Integer followId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column follow.userid
     *
     * @return the value of follow.userid
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column follow.userid
     *
     * @param userid the value for follow.userid
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column follow.follow_id
     *
     * @return the value of follow.follow_id
     *
     * @mbggenerated
     */
    public Integer getFollowId() {
        return followId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column follow.follow_id
     *
     * @param followId the value for follow.follow_id
     *
     * @mbggenerated
     */
    public void setFollowId(Integer followId) {
        this.followId = followId;
    }
}