package com.lx.model;

public class Message {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.userid
     *
     * @mbggenerated
     */

    private Integer messId;

    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.vid
     *
     * @mbggenerated
     */
    private Integer vid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.send_time
     *
     * @mbggenerated
     */
    private String sendTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.comment
     *
     * @mbggenerated
     */
    private String comment;


    private User user;

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public Integer getMessId() {
        return messId;
    }

    public void setMessId(Integer messId) {
        this.messId = messId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.userid
     *
     * @return the value of message.userid
     *
     * @mbggenerated
     */

    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.userid
     *
     * @param userid the value for message.userid
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.vid
     *
     * @return the value of message.vid
     *
     * @mbggenerated
     */
    public Integer getVid() {
        return vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.vid
     *
     * @param vid the value for message.vid
     *
     * @mbggenerated
     */
    public void setVid(Integer vid) {
        this.vid = vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.send_time
     *
     * @return the value of message.send_time
     *
     * @mbggenerated
     */
    public String getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.send_time
     *
     * @param sendTime the value for message.send_time
     *
     * @mbggenerated
     */
    public void setSendTime(String sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.comment
     *
     * @return the value of message.comment
     *
     * @mbggenerated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.comment
     *
     * @param comment the value for message.comment
     *
     * @mbggenerated
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    @Override
    public String toString() {
        return "Message{" +
                "messId=" + messId +
                ", userid=" + userid +
                ", vid=" + vid +
                ", sendTime='" + sendTime + '\'' +
                ", comment='" + comment + '\'' +
                ", user=" + user +
                '}';
    }
}