package com.lx.model;

public class UserCollectVideo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_collect_video.userid
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_collect_video.vid
     *
     * @mbggenerated
     */
    private Integer vid;

    private User user;
    private Video video;

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public Video getVideo() {
        return video;
    }

    public void setVideo(Video video) {
        this.video = video;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_collect_video.userid
     *
     * @return the value of user_collect_video.userid
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_collect_video.userid
     *
     * @param userid the value for user_collect_video.userid
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_collect_video.vid
     *
     * @return the value of user_collect_video.vid
     *
     * @mbggenerated
     */
    public Integer getVid() {
        return vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_collect_video.vid
     *
     * @param vid the value for user_collect_video.vid
     *
     * @mbggenerated
     */
    public void setVid(Integer vid) {
        this.vid = vid;
    }

    @Override
    public String toString() {
        return "UserCollectVideo{" +
                "userid=" + userid +
                ", vid=" + vid +
                ", user=" + user +
                ", video=" + video +
                '}';
    }
}