package com.lx.model;

public class UserPraiseIcon {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_praise_icon.state_praise
     *
     * @mbggenerated
     */
    private Integer statePraise;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_praise_icon.state_icon
     *
     * @mbggenerated
     */
    private Integer stateIcon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_praise_icon.userid
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_praise_icon.vid
     *
     * @mbggenerated
     */
    private Integer vid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_praise_icon.state_praise
     *
     * @return the value of user_praise_icon.state_praise
     *
     * @mbggenerated
     */
    public Integer getStatePraise() {
        return statePraise;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_praise_icon.state_praise
     *
     * @param statePraise the value for user_praise_icon.state_praise
     *
     * @mbggenerated
     */
    public void setStatePraise(Integer statePraise) {
        this.statePraise = statePraise;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_praise_icon.state_icon
     *
     * @return the value of user_praise_icon.state_icon
     *
     * @mbggenerated
     */
    public Integer getStateIcon() {
        return stateIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_praise_icon.state_icon
     *
     * @param stateIcon the value for user_praise_icon.state_icon
     *
     * @mbggenerated
     */
    public void setStateIcon(Integer stateIcon) {
        this.stateIcon = stateIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_praise_icon.userid
     *
     * @return the value of user_praise_icon.userid
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_praise_icon.userid
     *
     * @param userid the value for user_praise_icon.userid
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_praise_icon.vid
     *
     * @return the value of user_praise_icon.vid
     *
     * @mbggenerated
     */
    public Integer getVid() {
        return vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_praise_icon.vid
     *
     * @param vid the value for user_praise_icon.vid
     *
     * @mbggenerated
     */
    public void setVid(Integer vid) {
        this.vid = vid;
    }
}