package com.lx.model;

import java.sql.Timestamp;

public class Video {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.vid
     *
     * @mbggenerated
     */
    private Integer vid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.vname
     *
     * @mbggenerated
     */
    private String vname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.vsrc
     *
     * @mbggenerated
     */
    private String vsrc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.userid
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.praise
     *
     * @mbggenerated
     */
    private Integer praise;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.get_icon
     *
     * @mbggenerated
     */
    private Integer getIcon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.type_id
     *
     * @mbggenerated
     */
    private Integer typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.v_image
     *
     * @mbggenerated
     */
    private String vImage;

    private Timestamp vtime;

    public Timestamp getVtime() {
        return vtime;
    }

    public void setVtime(Timestamp vtime) {
        this.vtime = vtime;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.vid
     *
     * @return the value of video.vid
     *
     * @mbggenerated
     */

    


    public Integer getVid() {
        return vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.vid
     *
     * @param vid the value for video.vid
     *
     * @mbggenerated
     */
    public void setVid(Integer vid) {
        this.vid = vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.vname
     *
     * @return the value of video.vname
     *
     * @mbggenerated
     */
    public String getVname() {
        return vname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.vname
     *
     * @param vname the value for video.vname
     *
     * @mbggenerated
     */
    public void setVname(String vname) {
        this.vname = vname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.vsrc
     *
     * @return the value of video.vsrc
     *
     * @mbggenerated
     */
    public String getVsrc() {
        return vsrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.vsrc
     *
     * @param vsrc the value for video.vsrc
     *
     * @mbggenerated
     */
    public void setVsrc(String vsrc) {
        this.vsrc = vsrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.userid
     *
     * @return the value of video.userid
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.userid
     *
     * @param userid the value for video.userid
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.praise
     *
     * @return the value of video.praise
     *
     * @mbggenerated
     */
    public Integer getPraise() {
        return praise;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.praise
     *
     * @param praise the value for video.praise
     *
     * @mbggenerated
     */
    public void setPraise(Integer praise) {
        this.praise = praise;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.get_icon
     *
     * @return the value of video.get_icon
     *
     * @mbggenerated
     */
    public Integer getGetIcon() {
        return getIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.get_icon
     *
     * @param getIcon the value for video.get_icon
     *
     * @mbggenerated
     */
    public void setGetIcon(Integer getIcon) {
        this.getIcon = getIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.type_id
     *
     * @return the value of video.type_id
     *
     * @mbggenerated
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.type_id
     *
     * @param typeId the value for video.type_id
     *
     * @mbggenerated
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.v_image
     *
     * @return the value of video.v_image
     *
     * @mbggenerated
     */
    public String getvImage() {
        return vImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.v_image
     *
     * @param vImage the value for video.v_image
     *
     * @mbggenerated
     */
    public void setvImage(String vImage) {
        this.vImage = vImage;
    }

    @Override
    public String toString() {
        return "Video{" +
                "vid=" + vid +
                ", vname='" + vname + '\'' +
                ", vsrc='" + vsrc + '\'' +
                ", userid=" + userid +
                ", praise=" + praise +
                ", getIcon=" + getIcon +
                ", typeId=" + typeId +
                ", vImage='" + vImage + '\'' +
                ", vtime=" + vtime +
                '}';
    }
}